export default {
    Server: Symbol('Server'),
    Application: Symbol('Application'),
    IndexController: Symbol('IndexController'),
    DateController: Symbol('DateController'),
    IndexService: Symbol('IndexService'),
    DateService: Symbol('DateService'),
    DrawingController: Symbol('DrawingController'),
    DrawingService: Symbol('DrawingService'),
    TagService: Symbol('TagService'),
    TagController: Symbol('TagController'),
    DefService: Symbol('DefService'),
    DefController: Symbol('DefController'),
    MongoDbConnectionService: Symbol('MongoDbConnectionService'),
};
